# Generated by Django 2.1.7 on 2019-03-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='language',
            field=models.CharField(choices=[('ENU', 'English'), ('RUS', 'Russian')], default='ENU', help_text='Book language', max_length=3),
        ),
    ]
